apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: o7ps671ln-nodejs 
  janus-idp.io/tekton: o7ps671ln-nodejs
  backstage.io/kubernetes-id: o7ps671ln-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o7ps671ln-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml