apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: o7ps671ln-nodejs
  janus-idp.io/tekton: o7ps671ln-nodejs
  backstage.io/kubernetes-id: o7ps671ln-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o7ps671ln-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
